// Nepal-specific data for the job portal

const NEPAL_CITIES = [
  "Kathmandu",
  "Pokhara",
  "Biratnagar",
  "Lalitpur",
  "Bhaktapur",
  "Butwal",
  "Narayangadh",
  "Birgunj",
  "Janakpur",
  "Dharan",
  "Itahari",
  "Hetauda",
  "Dhangadhi",
  "Bhairahawa",
  "Mahendranagar",
  "Kailali",
  "Kanchanpur",
  "Jhapa",
  "Morang",
  "Sunsari",
];

const JOB_CATEGORIES = [
  "Information Technology",
  "Banking & Finance",
  "Teaching & Education",
  "Tourism & Hospitality",
  "Healthcare & Medical",
  "Engineering",
  "Marketing & Sales",
  "Administration & HR",
  "Construction & Real Estate",
  "Agriculture & Forestry",
  "Media & Communication",
  "Retail & Customer Service",
  "Software Development",
  "Data Science & Analytics",
  "Design & Creative",
  "Legal & Compliance",
];

const NEPAL_COMPANIES = [
  "Nabil Bank",
  "Nepal Telecom",
  "NIC Asia",
  "Himalayan Bank",
  "CG Corp Global",
  "Yeti Airlines",
  "Saurya Airlines",
  "BPC Limited",
  "NMB Bank",
  "Prime Bank",
  "Sanima Bank",
  "Laxmi Bank",
  "Global IME Bank",
  "Kumari Bank",
  "Siddhartha Bank",
  "NCC Bank",
  "Prabhu Bank",
  "Mega Bank",
  "Civil Bank",
  "Excel Development Bank",
];

const JOB_TYPES = ["full-time", "part-time", "contract", "internship"];

const EXPERIENCE_LEVELS = ["entry", "mid", "senior", "lead", "executive"];

const SKILLS = [
  "JavaScript",
  "React",
  "Node.js",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "SQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "AWS",
  "Docker",
  "Kubernetes",
  "Git",
  "HTML",
  "CSS",
  "Angular",
  "Vue.js",
  "Django",
  "Flask",
  "Spring Boot",
  "Laravel",
  "CodeIgniter",
  "Machine Learning",
  "Data Analysis",
  "Data Visualization",
  "Excel",
  "Power BI",
  "Tableau",
  "UI/UX Design",
  "Graphic Design",
  "Content Writing",
  "Digital Marketing",
  "SEO",
  "Social Media Management",
  "Project Management",
  "Agile",
  "Scrum",
  "Communication",
  "Leadership",
  "Teamwork",
  "Problem Solving",
];

module.exports = {
  NEPAL_CITIES,
  JOB_CATEGORIES,
  NEPAL_COMPANIES,
  JOB_TYPES,
  EXPERIENCE_LEVELS,
  SKILLS,
};
